project:
  type: website
  output-dir: public
  render:
    - "*.qmd"

website:
  page-navigation: true
  title: "Implementing {cards} in the QC Workflow"
  description: "Background on {cards}, {cardx}, {gtsummary}"
  favicon: "images/ard-c-logo.png"

  repo-url: https://github.com/insightsengineering/ard-catalog
  repo-actions: [edit, issue]

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#99B1C6"

  sidebar:
    background: "#99B1C6"
    logo: "images/ard-c-logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/insightsengineering/ard-catalog
        text: GitHub
    style: docked
    collapse-level: 1
    contents:
    - href: index.qmd
      text: Home
    - href: quarto/01-QC-DMT01.qmd
      text: Demographics Table
    - href: quarto/02-QC-AET02.qmd
      text: Adverse Events Table
    - href: quarto/03-QC-LBT01.qmd
      text: Lab Results Table
    - href: quarto/04-QC-TTET01.qmd
      text: Time-to-Event Table
    - href: quarto/05-formatting.qmd
      text: Formatting Statistics

format:
  html:
    theme: [cosmo, theme.scss]
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: source
