project:
  type: website
  output-dir: public
  render:
    - "*.qmd"

website:
  page-navigation: true
  title: "Implementing {cards} in the QC Workflow"
  description: "Background on {cards}, {cardx}, {gtsummary}"
  favicon: "images/ard-c-logo.png"

  repo-url: https://github.com/insightsengineering/ard-catalog
  repo-actions: [edit, issue]

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#99B1C6"

  sidebar:
    background: "#99B1C6"
    logo: "images/ard-c-logo.png"
    border: true
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/insightsengineering/ard-catalog
        text: GitHub
    style: docked
    collapse-level: 1
    contents:
        - file: index.qmd
          text: Introduction
        - text: "---"
        - auto: tables
        - text: "---"
        - auto: other
        - text: "---"

format:
  html:
    theme: [cosmo, theme.scss]
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: source
